name: Build-Push-Docker-Image

on:
  push:
    branches:
      - develop

jobs:
  build-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          push: true
          tags: |
            thierrymarianne/packetcrypt_rs:buster-slim
            thierrymarianne/packetcrypt_rs:latest
